# Generated by Django 3.2.7 on 2021-10-19 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20211019_1616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timetable',
            name='begin',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='end',
            field=models.DateTimeField(),
        ),
    ]
