# Generated by Django 3.2.7 on 2021-10-19 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_rename_user_student'),
        ('core', '0005_alter_timetable_abbreviation'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Group',
            new_name='Student_group',
        ),
    ]
